# Generated by Django 3.1.3 on 2020-12-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0013_article_book_fill_json_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='publications',
        ),
    ]
